import 'package:url_launcher/url_launcher.dart';

class EmailService {
  Future<bool> openEmailClient() async {
    try {
      final Uri emailUri = Uri(
        scheme: 'mailto',
        path: '',
        queryParameters: {
          'subject': 'PLC Inspection Export',
          'body': 'Generated by PLC Inspection app.',
        },
      );

      if (await canLaunchUrl(emailUri)) {
        await launchUrl(emailUri);
        return true;
      } else {
        print('No email app available');
        return false;
      }
    } catch (e) {
      print('Error opening email client: $e');
      return false;
    }
  }

  Future<bool> sendEmailWithAttachment({
    required String subject,
    required String body,
    required String attachmentPath,
  }) async {
    try {
      final Uri emailUri = Uri(
        scheme: 'mailto',
        queryParameters: {
          'subject': subject,
          'body': body,
        },
      );

      if (await canLaunchUrl(emailUri)) {
        await launchUrl(emailUri);
        return true;
      }
      return false;
    } catch (e) {
      print('Error sending email: $e');
      return false;
    }
  }
}