import 'package:flutter/material.dart';
import '../models/measurement.dart';
import '../services/database_service.dart';
import '../services/camera_service.dart';
import '../services/export_service.dart';
import '../services/email_service.dart';

class InspectionScreen extends StatefulWidget {
  const InspectionScreen({Key? key}) : super(key: key);

  @override
  State<InspectionScreen> createState() => _InspectionScreenState();
}

class _InspectionScreenState extends State<InspectionScreen> {
  late DatabaseService _dbService;
  late CameraService _cameraService;
  late ExportService _exportService;
  late EmailService _emailService;

  int _nextMeasureNo = 1;
  int _recordCount = 0;
  String _savedPhotoLocation = 'No photo yet';
  String _photoFilename = '';
  String _photoPath = '';

  final TextEditingController _descriptionController = TextEditingController();
  final TextEditingController _improvementController = TextEditingController();

  String _selectedPriority = 'MEDIUM';

  @override
  void initState() {
    super.initState();
    _dbService = DatabaseService();
    _cameraService = CameraService();
    _exportService = ExportService();
    _emailService = EmailService();
    _loadState();
  }

  Future<void> _loadState() async {
    try {
      final nextNo = await _dbService.getNextMeasureNo();
      final count = await _dbService.getMeasurementCount();
      setState(() {
        _nextMeasureNo = nextNo;
        _recordCount = count;
      });
    } catch (e) {
      _showErrorDialog('Error loading data: $e');
    }
  }

  Future<void> _takePhoto() async {
    try {
      final result = await _cameraService.captureAndSavePhoto(_nextMeasureNo);
      if (result != null) {
        setState(() {
          _photoFilename = result['filename']!;
          _photoPath = result['path']!;
          _savedPhotoLocation = result['path']!;
        });
        _showSuccessDialog('Photo Saved', 'Location: ${result['path']}');
      } else {
        _showErrorDialog('Camera permission denied or capture cancelled');
      }
    } catch (e) {
      _showErrorDialog('Error taking photo: $e');
    }
  }

  Future<void> _saveMeasurement() async {
    try {
      if (!['URGENT', 'SHORT', 'MEDIUM', 'LONG'].contains(_selectedPriority)) {
        _selectedPriority = 'MEDIUM';
      }

      final measurement = Measurement(
        measureNo: _nextMeasureNo,
        photoFilename: _photoFilename,
        photoPath: _photoPath,
        description: _descriptionController.text.trim(),
        improvementMeasure: _improvementController.text.trim(),
        priority: _selectedPriority,
        createdAt: DateTime.now(),
      );

      await _dbService.insertMeasurement(measurement);

      final nextNo = _nextMeasureNo + 1;
      await _dbService.updateNextMeasureNo(nextNo);

      setState(() {
        _nextMeasureNo = nextNo;
        _recordCount++;
        _savedPhotoLocation = 'No photo yet';
        _photoFilename = '';
        _photoPath = '';
        _selectedPriority = 'MEDIUM';
      });

      _descriptionController.clear();
      _improvementController.clear();
      _showSuccessDialog('Measurement Saved', 'Measure No. $_nextMeasureNo is ready.');
    } catch (e) {
      _showErrorDialog('Error saving measurement: $e');
    }
  }

  Future<void> _exportCSV() async {
    try {
      final measurements = await _dbService.getAllMeasurements();
      if (measurements.isEmpty) {
        _showErrorDialog('No measurements to export');
        return;
      }
      final filepath = await _exportService.exportToCSV(measurements);
      if (filepath != null) {
        _showSuccessDialog('CSV Exported', 'Location: $filepath');
      } else {
        _showErrorDialog('Error exporting CSV');
      }
    } catch (e) {
      _showErrorDialog('Error exporting CSV: $e');
    }
  }

  Future<void> _exportJSON() async {
    try {
      final measurements = await _dbService.getAllMeasurements();
      if (measurements.isEmpty) {
        _showErrorDialog('No measurements to export');
        return;
      }
      final filepath = await _exportService.exportToJSON(measurements);
      if (filepath != null) {
        _showSuccessDialog('JSON Exported', 'Location: $filepath');
      } else {
        _showErrorDialog('Error exporting JSON');
      }
    } catch (e) {
      _showErrorDialog('Error exporting JSON: $e');
    }
  }

  Future<void> _sendEmail() async {
    try {
      final success = await _emailService.openEmailClient();
      if (!success) {
        _showErrorDialog('No email app installed');
      } else {
        _showSuccessDialog('Email Client Opened', 'Subject: PLC Inspection Export\nBody: Generated by PLC Inspection app.');
      }
    } catch (e) {
      _showErrorDialog('Error opening email: $e');
    }
  }

  Future<void> _resetAll() async {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Clear All Data'),
        content: const Text('Are you sure? This will delete all measurements and reset the app.'),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () async {
              Navigator.pop(context);
              await _confirmReset();
            },
            child: const Text('Clear', style: TextStyle(color: Colors.red)),
          ),
        ],
      ),
    );
  }

  Future<void> _confirmReset() async {
    try {
      await _dbService.clearAllMeasurements();
      setState(() {
        _nextMeasureNo = 1;
        _recordCount = 0;
        _savedPhotoLocation = 'No photo yet';
        _photoFilename = '';
        _photoPath = '';
        _selectedPriority = 'MEDIUM';
      });
      _descriptionController.clear();
      _improvementController.clear();
      _showSuccessDialog('All Data Cleared', 'The app has been reset.');
    } catch (e) {
      _showErrorDialog('Error resetting app: $e');
    }
  }

  void _showSuccessDialog(String title, String message) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: Text(title),
        content: Text(message),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('OK'),
          ),
        ],
      ),
    );
  }

  void _showErrorDialog(String message) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Error'),
        content: Text(message),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('OK'),
          ),
        ],
      ),
    );
  }

  @override
  void dispose() {
    _descriptionController.dispose();
    _improvementController.dispose();
    _dbService.close();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('PLC Inspection'),
        elevation: 2,
        backgroundColor: Colors.blue[700],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: Colors.blue[50],
                borderRadius: BorderRadius.circular(8),
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text('Measure No: $_nextMeasureNo', style: Theme.of(context).textTheme.titleLarge),
                  Text('Records: $_recordCount', style: Theme.of(context).textTheme.bodyLarge),
                ],
              ),
            ),
            const SizedBox(height: 16),
            ElevatedButton.icon(
              onPressed: _takePhoto,
              icon: const Icon(Icons.camera_alt),
              label: const Text('TAKE PHOTO'),
              style: ElevatedButton.styleFrom(minimumSize: const Size(double.infinity, 50), backgroundColor: Colors.green[600]),
            ),
            const SizedBox(height: 8),
            Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(color: Colors.grey[100], borderRadius: BorderRadius.circular(8)),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text('Saved photo location:', style: TextStyle(fontSize: 12, color: Colors.grey)),
                  const SizedBox(height: 4),
                  Text(_savedPhotoLocation, style: Theme.of(context).textTheme.bodySmall, maxLines: 2, overflow: TextOverflow.ellipsis),
                ],
              ),
            ),
            const SizedBox(height: 16),
            TextField(
              controller: _descriptionController,
              decoration: InputDecoration(labelText: 'Description', hintText: 'Enter description', border: OutlineInputBorder(borderRadius: BorderRadius.circular(8))),
              maxLines: 3,
              textInputAction: TextInputAction.newline,
            ),
            const SizedBox(height: 16),
            TextField(
              controller: _improvementController,
              decoration: InputDecoration(labelText: 'Improvement Measure', hintText: 'Enter improvement action', border: OutlineInputBorder(borderRadius: BorderRadius.circular(8))),
              maxLines: 3,
              textInputAction: TextInputAction.newline,
            ),
            const SizedBox(height: 16),
            DropdownButtonFormField<String>(
              value: _selectedPriority,
              decoration: InputDecoration(labelText: 'Priority', border: OutlineInputBorder(borderRadius: BorderRadius.circular(8))),
              items: const [
                DropdownMenuItem(value: 'URGENT', child: Text('URGENT')), 
                DropdownMenuItem(value: 'SHORT', child: Text('SHORT')), 
                DropdownMenuItem(value: 'MEDIUM', child: Text('MEDIUM')), 
                DropdownMenuItem(value: 'LONG', child: Text('LONG'))
              ],
              onChanged: (value) {
                if (value != null) {
                  setState(() => _selectedPriority = value);
                }
              },
            ),
            const SizedBox(height: 16),
            ElevatedButton.icon(
              onPressed: _saveMeasurement,
              icon: const Icon(Icons.save),
              label: const Text('NEW MEASUREMENT'),
              style: ElevatedButton.styleFrom(minimumSize: const Size(double.infinity, 50), backgroundColor: Colors.blue[600]),
            ),
            const SizedBox(height: 16),
            Row(
              children: [
                Expanded(child: ElevatedButton.icon(onPressed: _exportCSV, icon: const Icon(Icons.download), label: const Text('CSV'), style: ElevatedButton.styleFrom(backgroundColor: Colors.orange[600]))),
                const SizedBox(width: 8),
                Expanded(child: ElevatedButton.icon(onPressed: _exportJSON, icon: const Icon(Icons.download), label: const Text('JSON'), style: ElevatedButton.styleFrom(backgroundColor: Colors.orange[600])))
              ],
            ),
            const SizedBox(height: 8),
            Row(
              children: [
                Expanded(child: ElevatedButton.icon(onPressed: _sendEmail, icon: const Icon(Icons.email), label: const Text('EMAIL'), style: ElevatedButton.styleFrom(backgroundColor: Colors.purple[600]))),
                const SizedBox(width: 8),
                Expanded(child: ElevatedButton.icon(onPressed: _resetAll, icon: const Icon(Icons.delete_forever), label: const Text('RESET'), style: ElevatedButton.styleFrom(backgroundColor: Colors.red[600])))
              ],
            ),
          ],
        ),
      ),
    );
  }
}